In [2]:
# what are ndarrays?
# they are just N-Dimensional matrices/arrays, but you gotta use numpy

import numpy as np

In [6]:
arr1 = np.array([4, 9, 16, 25, 36, 49]) # not `np.ndarray` bro.

arr2 = np.array([[1, 3, 5, 7, 9], [2, 4, 6, 8 , 10]]) # this is a two dimensional array.
print(arr1)

print(arr2)

[ 4  9 16 25 36 49]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [8]:
print(arr1*2)

l = [2, 3, 4]

print(l*2)

[ 8 18 32 50 72 98]
[2, 3, 4, 2, 3, 4]


### Indexing ndarrays

In [ ]:
# the first parameter is for dimensions, second is for the elements in that dimension.

print(arr2[0]) # should print the D1 array
print(arr2[1]) # should print the D2 array



[1 3 5 7 9]
[ 2  4  6  8 10]
