Series are nothing but single columns in a dataframe.
Damn.

So each series contain one type of data, and only that. So, doesn't matter if you give it a multi-dimensional array or dictionary, it will only be able to create one single row.

In [2]:
import pandas as pd

### Just creating a series

In [3]:
se = pd.Series([3, 4, 5], name="lol just checking", index=['no', 'hell no', 'f no'])

print(se)

no         3
hell no    4
f no       5
Name: lol just checking, dtype: int64


In [4]:
# what are ndarrays?
# they are just N-Dimensional matrices/arrays, but you gotta use numpy

import numpy as np

In [5]:
arr1 = np.array([4, 9, 16, 25, 36, 49]) # not `np.ndarray` bro.

arr2 = np.array([
    [1, 3, 5, 7, 9], 
    [2, 4, 6, 8 , 10]
    ]) # this is a two dimensional array.
    
print(arr1)

print(arr2)

[ 4  9 16 25 36 49]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


### Creating series from `ndarray`

In [6]:
se2 = pd.Series(arr1) #just put the array here. easy.

print(se2)

0     4
1     9
2    16
3    25
4    36
5    49
dtype: int64


In [7]:
se3 = pd.Series(arr2[1]) #from the first dimension.

print(se3)

0     2
1     4
2     6
3     8
4    10
dtype: int64


<!-- ### Creating from dictionaries -->

### Creating from dictionaries

In [8]:
car = {
    'brand': ['Ford', 'Hyundai'],
    'model': 'Mustang',
    'year': 1964
}

se4  = pd.Series(car["brand"]) #because it can accept only 1d stuff. 
print(se4)

se5 = pd.Series(car) # but if you give it a dict, then it will print the key (as index) - value pairs, which is quite useful. 
print(se5) 

0       Ford
1    Hyundai
dtype: object
brand    [Ford, Hyundai]
model            Mustang
year                1964
dtype: object


## Tail and Heads

*intuition*: heads = top, tail = bottom.

In [9]:
# lets take our old array `arr1` and its series `se2`

print(se2.tail(2)) # returns last 2 val
print(se2.head(2)) # returns first 2 val

# easy.


4    36
5    49
dtype: int64
0    4
1    9
dtype: int64


### Math with Series?

In [10]:
# let's take the same series as above, 

print(se2 + 2) # adds 2 to each value.
print(se2*2) # multiplies each value by 2.

#easy bro.

0     6
1    11
2    18
3    27
4    38
5    51
dtype: int64
0     8
1    18
2    32
3    50
4    72
5    98
dtype: int64


In [12]:
a_list = [1, 2, 4]

a_array = np.array([1, 2, 4])

print(a_list*2)

print(a_array*2)

[1, 2, 4, 1, 2, 4]
[2 4 8]


## Conditionals?

In [11]:
# same series
print(se2 > 12) # see if each element is >, <, >=, <= than a value. boolean.

print(se2.loc[lambda x : x>12])

se2.loc[lambda x : (x<40) & (x>12)]

0    False
1    False
2     True
3     True
4     True
5     True
dtype: bool
2    16
3    25
4    36
5    49
dtype: int64


2    16
3    25
4    36
dtype: int64