Series are nothing but single columns in a dataframe.
Damn.

So each series contain one type of data, and only that. So, doesn't matter if you give it a multi-dimensional array or dictionary, it will only be able to create one single row.

In [2]:
import pandas as pd # lol

### Just creating a series

In [3]:
se = pd.Series(
    [3, 4, 5], # the list of values
    name="lol just checking", # what we name the series
    index=['no', 'hell no', 'f no'] # we can specifically set index
)

print(se)

no         3
hell no    4
f no       5
Name: lol just checking, dtype: int64


In [4]:
# what are ndarrays?
# they are just N-Dimensional matrices/arrays, but you gotta use numpy

import numpy as np

In [5]:
arr1 = np.array([4, 9, 16, 25, 36, 49]) # not `np.ndarray` bro.    
print(arr1)

[ 4  9 16 25 36 49]


In [6]:
arr2 = np.array([
    [1, 3, 5, 7, 9], # level 1
    [2, 4, 6, 8 , 10] # level 2
    ]) # this is a two dimensional array.

print(arr2)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


### Creating series from `ndarray`

In [7]:
se2 = pd.Series(arr1) #just put the array here. easy.

print(se2)

0     4
1     9
2    16
3    25
4    36
5    49
dtype: int64


In [8]:
# which is the same as:

se2 = pd.Series(np.array([4, 9, 16, 25, 36, 49]))

print(se2)

0     4
1     9
2    16
3    25
4    36
5    49
dtype: int64


In [9]:
# for multidimensional arrays, you have to provide only one dimensional

se3 = pd.Series(arr2[1]) #from the first dimension.

print(se3)

0     2
1     4
2     6
3     8
4    10
dtype: int64


#### Creating multiple series from one `ndarray`

In [10]:
# suppose you have this multi-dimensional array:
arr3 = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
])

serieses = []

for array in arr3: # just iterate over the ndarray
    serieses.append(pd.Series(array)) # append to the empty series

print(serieses)

[0    1
1    2
2    3
3    4
dtype: int64, 0    5
1    6
2    7
3    8
dtype: int64, 0     9
1    10
2    11
3    12
dtype: int64]


<!-- ### Creating from dictionaries -->

### Creating from dictionaries

In [11]:
car = {
    'brand': ['Ford', 'Hyundai'],
    'model': 'Mustang',
    'year': 1964
}

se4  = pd.Series(car["brand"]) #because it can accept only 1d stuff. 
print(se4)

0       Ford
1    Hyundai
dtype: object


In [12]:
# but if you give it a dict, then it will print the key (as index) - value pairs, which is quite useful. 

se5 = pd.Series(car) 
print(se5) 

brand    [Ford, Hyundai]
model            Mustang
year                1964
dtype: object


## Accessing elements of a series

In [23]:
# Like lists and dictionaries, you can just ask for the index to get the element.

print(
    se2[4] # i am asking for the 3rd element (since, index begins at 0)
)

36


## Tail and Heads

*intuition*: heads = top, tail = bottom.

In [13]:
# lets take our old array `arr1` and its series `se2`

print(se2.head(2)) # returns first 2 values
# easy.

0    4
1    9
dtype: int64


In [14]:
print(se2.tail(2)) # returns last 2 values

4    36
5    49
dtype: int64


### Math with Series?

In [15]:
# let's take the same series as above, 

print(se2 + 2) # adds 2 to each value.
print(se2*2) # multiplies each value by 2.

# easy bro.

0     6
1    11
2    18
3    27
4    38
5    51
dtype: int64
0     8
1    18
2    32
3    50
4    72
5    98
dtype: int64


In [16]:
# lists vs arrays

a_list = [1, 2, 4]
a_array = np.array([1, 2, 4])

print(a_list*2)
print(a_array*2)

[1, 2, 4, 1, 2, 4]
[2 4 8]


## Conditionals

In [ ]:
# same series
print(
    se2 > 12 # see if each element is >, <, >=, <= than a value. boolean.
)

0    False
1    False
2     True
3     True
4     True
5     True
dtype: bool

In [ ]:
# use .loc[] and lambda to access the whole series and return each element if condition suffices

print(
    se2.loc[lambda x : x>12] # if x > 12, then print it.
)

2    16
3    25
4    36
5    49
dtype: int64

In [ ]:
print(
    se2.loc[lambda x : (x<40) & (x>12)] # if x < 40 AND x > 12
)

# make sure the ( ) are clear.

2    16
3    25
4    36
dtype: int64

In [ ]:
print(
    se2.loc[lambda x : (x%2 == 0) | (x%5 == 0)] # if x is even or a multiple of 5.
)

0     4
2    16
3    25
4    36
dtype: int64
